copy bootrom.bin dist
copy font.png dist
copy boot.png dist
copy bin\wget.exe dist
copy bin\full.bat dist
copy bin\server.bat dist
copy bin\server.sh dist
copy bin\client.bat dist
copy bin\client.sh dist
copy world.xml dist
